### ISSUE TITLE
Refactor Twitter NRTS package to use Jetty servlets

### ISSUE THREAD

**Issue by lintool** [lintool/Anserini#13]
The current implementation of [TweetSearcherServer](https://github.com/lintool/Anserini/blob/master/src/main/java/io/anserini/nrts/TweetSearcherServer.java) parses raw HTTP requests. 

We should use a proper servlet container like Jetty:
http://www.eclipse.org/jetty/

Example of embedded servlet:
http://www.eclipse.org/jetty/documentation/9.1.4.v20140401/embedded-examples.html#embedded-minimal-servlet

**Comment by xeniaqian94** [comment]
The refactoring part was pulled as a request. 

However, for one thing, the original implementation of TweetSearcherServer used thread pool mechanism. Once we switch to Jetty servlet, thread pool mechanism would be unnecessary? Since some of the discussion about Jetty servlet suggests it handles incoming requests in multithread implicitly. 

https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg01212.html 
"what your running into is that once a request enters into the servlet api, it has a thread allocated to it for its lifetime in the servlet-api prior to servlet 3.0 where the concept of async was supported.  continuations is a mechanism that allows for a similar mechanic on jetty in servlet 2.5 and yes, jetty is multithreaded."

**Comment by lintool** [comment]
Commented on pull request.
Yes, I believe Jetty handles async requests behind the scenes.

**Comment by lintool** [comment]
Merged. commit 89a7daab03b360104c44e4fbf123162fce945efe
