### ISSUE TITLE
Refactoring of the index and document

### ISSUE THREAD

**Issue by Peilin-Yang** [lintool/Anserini#78]
For now everything is based on Warc formatted records.
We'd have other types of records too, e.g. Trec text or maybe other types in the future.
It is better to have a base record and everything inherits it.

**Comment by lintool** [comment]
@Peilin-Yang For the TREC documents, you might want to consider what we did for the IR-reproducibility experiments: https://github.com/lintool/IR-Reproducibility/tree/master/systems/lucene/ingester/src/main/java/luceneingester

IIRC, there the code uses an actual XML parser instead of string parsing...

**Comment by Peilin-Yang** [comment]
I think you rely on some Lucene code to do the parsing (https://github.com/lintool/IR-Reproducibility/blob/master/systems/lucene/ingester/src/main/java/luceneingester/IndexThreads.java#L25-L27)?

Yes, Lucene has an arsenal of parsing different old TREC collections, e.g. GOV2, LATimes, FT, FBIS, etc.
https://github.com/apache/lucene-solr/tree/master/lucene/benchmark/src/java/org/apache/lucene/benchmark/byTask/feeds

It will be interesting to look into it.

**Comment by lintool** [comment]
Yes, we should copy that code and integrate/refactor in Anserini.

**Comment by Peilin-Yang** [comment]
Merged
